spring:
  application:
    name: ib-core-service
  main:
    banner-mode: "off"
    
################ DB MYSQL ################
  datasource:
    url: jdbc:mysql://localhost:3306/app_soc?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
################ DB MYSQL ################
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect